version: '3.8'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser_app
    ports:
      - "8082:80"
    volumes:
      - /home/muzz/my_serverku:/srv
      - ../../../app-storages/file_browser/filebrowser.db:/database/filebrowser.db
      - ../../../app-storages/file_browser/settings.json:/config/settings.json
    restart: always