services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:latest
    container_name: suwayomi_server
    ports:
      - "4567:4567"
    volumes:
      - ../../../app-storages/suwayomi:/home/suwayomi/.local/share/Tachidesk
    environment:
      - TZ=Asia/Jakarta
      # Mencegah Java Virtual Machine menyedot habis sisa RAM
      - JAVA_TOOL_OPTIONS= -Xmx512m -Xms256m
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700M
    depends_on:
      - flaresolverr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
    restart: unless-stopped
    deploy:
      resources:
        limits:
          # Kasih batas biar gak nyedot RAM server lu sampai mati
          memory: 500M