services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser_app
    ports:
      - "8082:80"
    volumes:
      - /home/muzz/my_serverku:/srv         # Mengarahkan FileBrowser untuk bisa melihat seluruh folder server lu
      - ./filebrowser.db:/database/filebrowser.db
      - ./config.json:/config/config.json
    restart: unless-stopped