services:
  couchdb:
    image: apache/couchdb:3
    container_name: couchdb_obsidian
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ../../../app-storages/couch_db_obsidian/data:/opt/couchdb/data
      - ../../../app-storages/couch_db_obsidian/etc:/opt/couchdb/etc/local.d