version: '3.8'

services:
  tabby-web:
    image: ghcr.io/eugeny/tabby-web:latest
    container_name: tabby_app
    ports:
      - "8000:8000" # <--- LUAR: 8000 dikembalikan ke INTERNAL: 8000
    environment:
      - DATABASE_URL=sqlite:////app/data/db.sqlite3 
      - PORT=8000 
      - ALLOWED_HOSTS=192.168.1.24,localhost,127.0.0.1,tabby.barr.my.id
      - APP_URL=https://tabby.barr.my.id
    volumes:
      - ../../../app-storages/tabby-web/data:/app/data
    restart: always