services:
  jdownloader:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader_app
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Jakarta
    volumes:
      - ../../../app-storages/jdownloader/config:/config:rw
      - ../../../Drive/Downloads:/output:rw
    ports:
      - 5800:5800
    restart: unless-stopped