services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_app
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Jakarta
      - WEBUI_PORT=8085
      - TORRENTING_PORT=6881
    volumes:
      - ../../../app-storages/qbittorrent/config:/config
      - ../../../Drive/Downloads:/downloads
    ports:
      - 8085:8085
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped