services:
  linkstack:
    image: linkstackorg/linkstack:latest
    container_name: linkstack_app
    ports:
      - "8190:80"
    volumes:
      - ../../../app-storages/linkstack/linkstack_data:/htdocs
    restart: always