
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale_container
    hostname: acer-server
    environment:
      - TS_USERSPACE=false
      - TS_AUTHKEY= ${TAILSCALE_AUTHKEY}
    volumes:
      - ../../../app-storages/tailscale/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"
    restart: always
